config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'agreement', to: 'pages#agreement'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :courses, only: [:index, :show] do
	  resources :bookings, only: [:create]
  end
  namespace :dashboard do
	  resources :bookings, only: [:index]
  end
  resources :bookings, only: [:update]
  resources :chef_profiles, only: [:show, :create] do
	  resources :courses, only: [:new, :create]
  end
end

app/views/shared/_booking-card.html.erb
<div class="card-trip card-trip-overflow mb-3 d-flex flex-column justify-content-between">
  <%= header_image_tag %>
  <%= link_to course_path(booking.course) do %>
    <div class="card-trip-infos">
      <div class="card-text-wrap text-truncate">
        <div class="d-flex flex-column justify-content-between h-100">
          <h2><%= title %></h2>
          <p class="text-capitalize"><em><%= sub_title %></em></p>
          <p><%= description %></p>
        </div>
      </div>
      <div class="w-100 text-right mt-1">
        <h2 class="card-trip-text-padding"><%= status %></h2>
      </div>
      <%= user_image_tag %>
    </div>
  <% end %>
  <div id="booking-respond-row" class="justify-content-end">
    <% if status == 'confirmed' %>
      <div class="mx-2 mb-2">
        <%= simple_form_for booking do |f| %>
          <%= f.input :status, as: :hidden, input_html: { value: 'completed'}, wrapper_html: { class: "py-0 my-0"} %>
          <%= f.submit "I'm happy :)", class: 'btn btn-success btn-sm w-100' %>
        <% end %>
      </div>
      <div class="mx-2 mb-2">
        <%= simple_form_for booking do |f| %>
          <%= f.input :status, as: :hidden, input_html: { value: 'completed'}, wrapper_html: { class: "py-0 my-0"} %>
          <%= f.submit 'Could be better :|', class: 'btn btn-warning btn-sm w-100' %>
        <% end %>
      </div>
      <div class="mx-2 mb-2">
        <%= simple_form_for booking do |f| %>
          <%= f.input :status, as: :hidden, input_html: { value: 'completed'}, wrapper_html: { class: "py-0 my-0"} %>
          <%= f.submit "I'm not impressed :(", class: 'btn btn-danger btn-sm w-100' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_carousel-course.html.erb
<div id="carouselCourseList<%= card_count %>Controls" class="carousel slide p-2 mb-0 rounded carousel-movie-base" data-ride="carousel">
  <div class="carousel-inner">
    <%  courses.each_slice(card_count) do |s_course| %>
      <div class="carousel-item<%= courses.first == s_course[0] ? " active" : "" %>">
        <div class="cards py-2 px-2">
          <%  s_course.each do |course| %>
            <%= link_to course_path(course) do %>
              <% initial = course.chef_profile.user.first_name.nil? ? course.chef_profile.user.email[0].upcase : course.chef_profile.user.first_name[0].upcase; %>
              <% header_image_tag = course.photo.attached? ? cl_image_tag(course.photo.key)
                : cl_image_tag("https://dummyimage.com/1000x500/fff/000&text=Sorry!%20No%20photo%20attached",type: "fetch") %>
              <% user_image_tag = course.chef_profile.user.photo.attached? ? cl_image_tag(course.chef_profile.user.photo.key, class: "card-trip-user avatar-bordered", aspect_ratio: "1.0", crop: :thumb)
                : cl_image_tag("https://dummyimage.com/200x200/fff/000&text=#{initial}",type: "fetch", class: "card-trip-user avatar-bordered") %>
              <% render 'shared/square-card', title: course.name, status: "¥#{number_with_delimiter(course.price)}", 
                      header_image_tag: header_image_tag,
                      user_image_tag: user_image_tag %>
            <% end %>
          <% end %>
          <!-- Add empty card to prevent carousel from collapsing when resize the screen (to keep it 4x1 or 2x2)-->
          <% if s_course.count < card_count %>
            <% (card_count - s_course.count).times do %>
              <div class="card-category card-category-bg invisible"></div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev small-carousel-btn" href="#carouselCourseList<%= card_count %>Controls" role="button" data-slide="prev">
    <span class="" aria-hidden="true"><i class="fas fa-chevron-left"></i></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next small-carousel-btn" href="#carouselCourseList<%= card_count %>Controls" role="button" data-slide="next">
    <span class="" aria-hidden="true"><i class="fas fa-chevron-right"></i></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_chef-information-card.html.erb
<div class="card-trip mb-3 d-flex flex-column justify-content-between" id="card-trip-flow">
  <%= header_avatar_tag %>
  <div class="card-trip-infos">
    <div class="card-text">
      <div class="d-flex flex-column justify-content-between h-100">
        <h2><%= title %></h2>
        <p class="text-capitalize"><strong><%= sub_title %></strong></p>
      </div>
    </div>
    <div class="w-100 text-right mt-1">
      <h2 class="card-trip-text-padding"><%= status %></h2>
    </div>
  </div>
  <div class="mb-0 pb-0 px-2">
    <h2>More by this chef</h2>
  </div>
  <div class="pt-0">
    <div class="carousel-4">
      <%= render 'shared/carousel-course', courses: @course.chef_profile.courses, card_count: 4 %>
    </div>
    <div class="carousel-2">
      <%= render 'shared/carousel-course', courses: @course.chef_profile.courses, card_count: 2 %>
    </div>
  </div>
</div>

app/views/shared/_course-card.html.erb
<div class="card-trip mb-3 d-flex flex-column justify-content-between">
  <%= header_image_tag %>
  <div class="card-trip-infos">
    <div class="card-text-wrap text-truncate">
      <div class="d-flex flex-column justify-content-between h-100">
        <div>
          <h2><%= title %></h2>
          <p class="text-capitalize"><em><%= sub_title %></em></p>
          <p><%= description %></p>
        </div>
        <div class="w-100 text-right mt-1">
          <h2 class="card-trip-text-padding"><%= status %></h2>
        </div>
      </div>
    </div>
    <%= user_image_tag %>
  </div>
</div>

app/views/shared/_course-confirm-card.html.erb
<div class="card-trip mb-3 d-flex flex-column justify-content-between">
  <%= header_image_tag %>
  <div class="card-trip-infos">
    <div class="d-flex flex-column justify-content-between h-100">
      <div class="card-text-wrap text-truncate">
        <h2><%=  booking.course.name %></h2>
        <p><%= booking.date_and_start_time %></p>
      </div>
      <div class="w-100 text-right">
        <% if booking.status == "awaiting confirmation" %>
          <div class="d-flex justify-content-end">
            <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: { value: 'confirmed'} %>
              <%= f.submit 'Confirm', class: 'btn btn-success btn-sm mx-2' %>
            <% end %>
            <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: { value: 'declined'} %>
              <%= f.submit 'Decline', class: 'btn btn-danger btn-sm' %>
            <% end %>
          </div>
        <% else %>
          <h2 class="card-trip-text-padding"><%= booking.status %></h2>
        <% end %>
      </div>
    </div>
    <%= user_image_tag %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_fullpage-card.erb
<div class="card-trip mb-3 d-flex flex-column justify-content-between" id="card-trip-flow">
  <%= header_image_tag %>
  <div class="card-trip-infos">
    <div class="card-text">
      <div class="d-flex flex-column justify-content-between h-100">
        <h2><%= title %></h2>
        <p class="text-capitalize"><strong><%= sub_title %></strong></p>
        <p><%= description %></p>
      </div>
      <div class="w-100 text-right mt-1">
        <h2 class="card-trip-text-padding"><%= status %></h2>
      </div>
    </div>
    <%= user_image_tag %>
  </div>
</div>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="<%= modal_id %>Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="<%= modal_id %>Label"><%= modal_title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if text_header %>
          <h5><%= text_header %></h5>
        <% end %>
        <p><%= text_body %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to redirect_path do %>
          <button type="button" class="btn btn-primary" data-dismiss="modal"><%= btn_modal_confirm %></button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-static-top navbar-light bg-light d-flex justify-content-between">
  <%= link_to root_path do %>
    <span class="navbar-brand mb-0 h1"><i class="fas fa-glass-cheers"></i> TY, Chef!</span>
  <% end %>
  <% if current_user.nil? %>
    <p id="nav-welcome-text" class="my-auto">Are you hungry?</p>
    <% cl_image = cl_image_tag("https://dummyimage.com/25x25/fff/000&text=%3F",
      type: "fetch", class: "rounded-circle my-auto") %>
  <% else %>
    <% username = current_user.first_name || current_user.email.split('@')[0] %>
    <p id="nav-welcome-text" class="my-auto">Are you hungry, <%= username %>?</p>
    <% if current_user.photo.attached? %>
      <% cl_image = cl_image_tag(current_user.photo.key, class: "rounded-circle my-auto", width: 24, height: 24, aspect_ratio: "1.0", crop: :thumb) %>
    <% else %>
      <% initial = current_user.first_name.nil? ? chef.user.email[0].upcase : current_user.first_name[0].upcase; %>
      <% cl_image = cl_image_tag("https://dummyimage.com/25x25/fff/000&text=#{initial}",
      type: "fetch", class: "rounded-circle my-auto") %>
    <% end %>
  <% end %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle px-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= cl_image %>
      <i class="fas fa-bars"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <% if user_signed_in? %>
        <%= link_to dashboard_bookings_path do %>
          <p class="dropdown-item">My Booking</p>
        <% end %>
        <%= link_to edit_user_registration_path do %>
          <p class="dropdown-item">Update my profile</p>
        <% end %>
        <% if current_user.chef? %>
          <%= link_to chef_profile_path(current_user.chef_profile) do %>
            <p class="dropdown-item">[Manage my courses]</p>
          <% end %>
          <%= link_to dashboard_bookings_path + '?chefdashboard' do %>
            <p class="dropdown-item">[Manage my bookings]</p>
          <% end %>
        <% else %>
          <%= link_to agreement_path do %>
            <p class="dropdown-item">[Become a Chef]</p>
          <% end %>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <% end %>
    </div>
  </li>
</nav>

app/views/shared/_square-card.html.erb
<div class="card-trip mb-3 d-flex flex-column justify-content-between">
  <%= header_image_tag %>
  <div class="card-trip-infos">
    <div class="d-flex flex-column justify-content-between h-100">
      <h2><%= title %></h2>
      <h2 class="w-100 text-right mt-1"><%= status %></h2>
    </div>
    <%= user_image_tag %>
  </div>
</div>